export const theme = {
  colors: {
    background: '#EEF2F7',
    card: '#FFFFFF',
    primary: '#1B3A6B',
    accent: '#2563EB',
    success: '#16A34A',
    successBg: '#DCFCE7',
    error: '#DC2626',
    errorBg: '#FEE2E2',
    warning: '#D97706',
    warningBg: '#FEF3C7',
    textPrimary: '#0F172A',
    textMuted: '#64748B',
    divider: '#E2E8F0',
    inputBorder: '#CBD5E1',
    neutralLight: '#F1F5F9',
    neutralMuted: '#94A3B8',
    overlayLight: 'rgba(255, 255, 255, 0.7)',
    backgroundAlt: '#F8FAFC',
    disabled: '#94A3B8',
    transparent: 'transparent',
  },
  typography: {
    fontFamily: 'Hanken Grotesk',
    sizes: {
      title: 22,
      subtitle: 16,
      body: 14,
      caption: 12,
    },
  },
  styles: {
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    button: {
      backgroundColor: '#1B3A6B',
      borderRadius: 999,
      paddingVertical: 14,
      paddingHorizontal: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonOutline: {
      backgroundColor: 'transparent',
      borderColor: '#1B3A6B',
      borderWidth: 1.5,
      borderRadius: 999,
      paddingVertical: 14,
      paddingHorizontal: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonText: {
      color: '#FFFFFF',
      fontWeight: 'bold' as const,
      fontSize: 15,
    },
    buttonOutlineText: {
      color: '#1B3A6B',
      fontWeight: 'bold' as const,
      fontSize: 15,
    },
    badge: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: '600' as const,
    },
    input: {
      borderColor: '#CBD5E1',
      borderWidth: 1,
      borderRadius: 10,
      padding: 12,
      fontSize: 15,
      color: '#0F172A',
      backgroundColor: '#FFFFFF',
    },
  },
};
export type Theme = typeof theme;
